version: "3.9"
services:
  rabbitmq-server:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
      - 5674:5672
      - 15674:15672

  meter:
    build: .
    command: python -m main.py meter
    links:
      - "rabbitmq-server:rabbitmq-server"
    depends_on:
      - "rabbitmq-server"

  pv_simulator:
    build: .
    command: python -m main.py pv_simulator
    links:
      - "rabbitmq-server:rabbitmq-server"
    depends_on:
      - "rabbitmq-server"
