version: "3.9"
services:
  rabbitmq-server:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
      - 5674:5672
      - 15674:15672
  meter:
    container_name: meter
    build: .

  pvsimulator:
    container_name: pvsimulator
    build: .
