version: "3"
services:
  rabbitmq-server:
    container_name: rabbitmq
    image: rabbitmq:3.9-management
    ports:
      - 5674:5672
      - 15674:15672

  meter:
    build: .
    volumes:
      - ./:/code
    command: python App/main.py meter
    links:
      - "rabbitmq-server:rabbitmq-server"
    depends_on:
      - "rabbitmq-server"

  pv_simulator:
    build: .
    volumes:
      - ./:/code
    command: python App/main.py pv_simulator
    links:
      - "rabbitmq-server:rabbitmq-server"
    depends_on:
      - "rabbitmq-server"